apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ntxuuggv4-go 
  janus-idp.io/tekton: ntxuuggv4-go
  backstage.io/kubernetes-id: ntxuuggv4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntxuuggv4-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml